name: Server deploy
on: [push]
jobs:
  terraform-deployment:
    runs-on: ubuntu-latest
    steps:
      # EXPORT THE CREDENTIALS - MARKETPLACE : "Configure AWS Credentials ACTION  GitHub Actions"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Clone/Checkout your repository code infra
        uses: actions/checkout@v2
        working-directory: ./infrastructure

      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
        working-directory: ./infrastructure

      - name: Terraform init
        run: terraform init
        working-directory: ./infrastructure

      - name: Terraform plan
        run: terraform plan
        working-directory: ./infrastructure